spring:
  datasource:
    url: jdbc:mysql://hedgebanan.beget.tech:3306/hedgebanan_conta?noAccessToProcedureBodies=true
    username: hedgebanan_conta
    password: hedgebanan_conta123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: smtp.beget.com
    port: 2525
    username: atg.company@keban.xyz
    password: mi6&Y6NNG70q
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8081
authentication:
  app:
    jwtSecret: mySuperSecretAndLongKey123!@!$DSHJKFDSKFHJKbsdjdkbkjhHFHGgkJGHFhjCNVBGJBHJJGHJgKBKJ
    jwtExpirationMs: 43200000
pdf:
  directory: backAPI/src/main/resources/Factures